"""initial schema

Revision ID: c76f66fba9ea
Revises: 
Create Date: 2026-05-30 14:14:31.399238
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c76f66fba9ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bar_size', sa.String(length=8), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('feature_set_version', sa.String(length=24), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('data_confidence_score', sa.Float(), nullable=False),
    sa.Column('missing_data_flag', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ts', 'bar_size', name='uq_feature_snapshot')
    )
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_snapshots_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_snapshots_ts'), ['ts'], unique=False)

    op.create_table('model_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_set_version', sa.String(length=24), nullable=False),
    sa.Column('metric_name', sa.String(length=48), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('window', sa.String(length=24), nullable=True),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_performance_model_name'), ['model_name'], unique=False)

    op.create_table('raw_news_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_news_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_news_results_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_news_results_ticker'), ['ticker'], unique=False)

    op.create_table('raw_price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('bar_size', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'bar_size', 'ts', name='uq_price_bar')
    )
    with op.batch_alter_table('raw_price_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_price_data_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_price_data_ts'), ['ts'], unique=False)

    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_ts'), ['ts'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('logger', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_ts'), ['ts'], unique=False)

    op.create_table('final_signals',
    sa.Column('signal_id', sa.String(length=40), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('p_downside', sa.Float(), nullable=True),
    sa.Column('adjusted_p_downside', sa.Float(), nullable=True),
    sa.Column('base_downside_risk_score', sa.Float(), nullable=True),
    sa.Column('adjusted_downside_risk_score', sa.Float(), nullable=True),
    sa.Column('model_agreement_score', sa.Float(), nullable=True),
    sa.Column('data_confidence_score', sa.Float(), nullable=True),
    sa.Column('price_volume_confirmation', sa.Float(), nullable=True),
    sa.Column('news_shift_logodds', sa.Float(), nullable=True),
    sa.Column('expected_edge_bps', sa.Float(), nullable=True),
    sa.Column('uncertainty_penalty', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('governance', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.String(length=12), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=False),
    sa.Column('feature_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('actual_return_24h', sa.Float(), nullable=True),
    sa.Column('prediction_correct', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ),
    sa.PrimaryKeyConstraint('signal_id')
    )
    with op.batch_alter_table('final_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_signals_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_signals_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_signals_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_signals_ts'), ['ts'], unique=False)

    op.create_table('structured_news_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_news_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('recency_score', sa.Float(), nullable=False),
    sa.Column('company_specificity_score', sa.Float(), nullable=False),
    sa.Column('expected_direction', sa.String(length=12), nullable=False),
    sa.Column('expected_impact_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('scorer', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['raw_news_id'], ['raw_news_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('structured_news_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structured_news_scores_scored_at'), ['scored_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_structured_news_scores_ticker'), ['ticker'], unique=False)

    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=48), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_set_version', sa.String(length=24), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['final_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_ts'), ['ts'], unique=False)

    op.create_table('paper_trades',
    sa.Column('trade_id', sa.String(length=40), nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('position_notional', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=24), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=8), nullable=True),
    sa.Column('market_regime', sa.String(length=16), nullable=True),
    sa.Column('attribution', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['final_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trades_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_ticker'), ['ticker'], unique=False)

    op.create_table('post_trade_attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('market_component', sa.Float(), nullable=True),
    sa.Column('sector_component', sa.Float(), nullable=True),
    sa.Column('company_component', sa.Float(), nullable=True),
    sa.Column('dominant_driver', sa.String(length=24), nullable=True),
    sa.Column('prediction_correct', sa.Boolean(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['final_signals.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_trade_attribution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_trade_attribution_signal_id'), ['signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_trade_attribution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_trade_attribution_signal_id'))

    op.drop_table('post_trade_attribution')
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trades_ticker'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_signal_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_mode'))

    op.drop_table('paper_trades')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_ts'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_ticker'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_signal_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('structured_news_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structured_news_scores_ticker'))
        batch_op.drop_index(batch_op.f('ix_structured_news_scores_scored_at'))

    op.drop_table('structured_news_scores')
    with op.batch_alter_table('final_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_signals_ts'))
        batch_op.drop_index(batch_op.f('ix_final_signals_ticker'))
        batch_op.drop_index(batch_op.f('ix_final_signals_mode'))
        batch_op.drop_index(batch_op.f('ix_final_signals_decision'))

    op.drop_table('final_signals')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_ts'))

    op.drop_table('system_logs')
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_events_ts'))

    op.drop_table('risk_events')
    with op.batch_alter_table('raw_price_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_price_data_ts'))
        batch_op.drop_index(batch_op.f('ix_raw_price_data_ticker'))

    op.drop_table('raw_price_data')
    with op.batch_alter_table('raw_news_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_news_results_ticker'))
        batch_op.drop_index(batch_op.f('ix_raw_news_results_fetched_at'))

    op.drop_table('raw_news_results')
    with op.batch_alter_table('model_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_performance_model_name'))

    op.drop_table('model_performance')
    with op.batch_alter_table('feature_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_ts'))
        batch_op.drop_index(batch_op.f('ix_feature_snapshots_ticker'))

    op.drop_table('feature_snapshots')
    # ### end Alembic commands ###
